### ISSUE TITLE
Create Discord invite link

### ISSUE THREAD

**Issue by BrooklinJazz** [BrooklinJazz/elixir_newbie_website_v2#18]
Create a page with a button to join the Elixir Newbie Discord.

Add auto moderation to the Elixir Newbie Discord

@bigspaces is assigned. Remind me to add you as a contributor

**Comment by IciaCarroBarallobre** [comment]
This discord link in home page works for me:
![imagen](https://user-images.githubusercontent.com/47258107/222283327-f6894ffb-8c65-436c-b6a9-81eb98975a12.png)

But this other in `/resources`, it doesn't work (at least, for me):

> The following link to the[ Student Setup Guide ](https://github.com/DockYard-Academy/beta_curriculum/wiki/Student-Setup-Guide)will provide the steps to create an Elixir development environment.
For support with setting up the curriculum with livebook as well as with the many concepts in the course material visit us on the Elixir Newbie Discord Server[ here ](https://discord.gg/VzF8fHAC).

![imagen](https://user-images.githubusercontent.com/47258107/222283483-b13763c7-d11c-4aa5-b4df-272c1815e93a.png)
