### ISSUE TITLE
Create Blog page

### ISSUE THREAD

**Issue by BrooklinJazz** [BrooklinJazz/elixir_newbie_website_v2#19]
Edit old blogs to improve the consistency of the content. Replace images with actual code snippets.

Allow guests posts with author name and their image.

Default the image to a unique identicon (like github) udemy w/stephen grider has a great tutorial.

Potentially dynamically retrieve my blogs from medium/dev.to

**Comment by fabrithedev** [comment]
Hey @BrooklinJazz !

I would like to work on this one.
My first idea is to replicate the blog page of previous site using the new layout. After this start working on the requirements above. What do you think?

**Comment by fabrithedev** [comment]
I didint found in figma a complete layout for blog list. Trying few things but im not good at design at all ;)

![blog](https://user-images.githubusercontent.com/3181570/217701153-4f71cb45-e538-401e-b611-639130b6189f.gif)

**Comment by BrooklinJazz** [comment]
I have a figma design I can share with you! I'm away from my keys right now, but will send you a link as soon as I can.

**Comment by BrooklinJazz** [comment]
Actually, it looks like you already found it. Fantastic!

**Comment by BrooklinJazz** [comment]
Would love for you to tackle this feature. I'm here to support you however I can help.

**Comment by fabrithedev** [comment]
@BrooklinJazz 

I've made some advancements with the blog list. I'll appreciate your feedback
The code is in my fork on blog branch:
https://github.com/FabriDamazio/elixir_newbie_website_v2/tree/blog

![image](https://user-images.githubusercontent.com/3181570/218096135-cb4c71d8-5fd0-45b7-a5ba-4ad33947c180.png)

**Comment by BrooklinJazz** [comment]
Great! Will make comments as soon as I have some time this weekend

**Comment by BrooklinJazz** [comment]
@FabriDamazio for future review, can you make a DRAFT pull request to make it easier for me to review changes?

**Comment by BrooklinJazz** [comment]
In seeing the code today I think you're making great progress.

I'd like to slightly change the spacing on the blog cards (the title is a bit close to the image) but otherwise it's absolutely perfect!

I look forward to seeing the search feature after today's session!

**Comment by fabrithedev** [comment]
> @FabriDamazio for future review, can you make a DRAFT pull request to make it easier for me to review changes?

sure i fogot this feature
